services:

  postgres:
    image: postgres:16
    container_name: encode-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: encode_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Encode.Api/Dockerfile

    container_name: encode-api

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__Default: Host=postgres;Port=5432;Database=encode_db;Username=postgres;Password=postgres

      Jwt__Key: super-secret-jwt-key-with-at-least-32-characters

    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: encode-frontend

    restart: unless-stopped

    depends_on:
      - api

    ports:
      - "4200:4200"

volumes:
  postgres_data: